name       : python-cssselect2
version    : 0.7.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/e7/fc/326cb6f988905998f09bb54a3f5d98d4462ba119363c0dfad29750d48c09/cssselect2-0.7.0.tar.gz : 1ccd984dab89fc68955043aca4e1b03e0cf29cad9880f6e28e3ba7a74b14aa5a
license    : BSD-3-Clause
homepage   : https://doc.courtbouillon.org/cssselect2/stable/
component  : programming.python
summary    : CSS selectors for Python ElementTree
description: |
    cssselect2 is a straightforward implementation of CSS4 Selectors for markup documents (HTML, XML, etc.) that can be read by ElementTree-like parsers (including cElementTree, lxml, html5lib, etc.)
builddeps  :
    - python-pytest #check
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
    - python-tinycss2
    - python-webencodings
    - python-wheel
rundeps    :
    - python-tinycss2
    - python-webencodings
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    python3 -m pytest
